# Generated by Django 5.2.6 on 2026-01-11 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0001_initial"),
        ("transactions", "0002_transaction_blockchain_tx_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditwallet",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="The transaction that created this credit entry (for purchased credits)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_wallets",
                to="transactions.transaction",
            ),
        ),
    ]
