# Generated by Django 5.2.6 on 2026-01-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0002_creditwallet_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditwallet",
            name="price_per_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per credit in INR at time of purchase/listing",
                max_digits=10,
                null=True,
            ),
        ),
    ]
