# Generated by Django 5.2.9 on 2025-12-30 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField()),
                ('project_name', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('SOLAR', 'Solar'), ('PLANTATION', 'Plantation'), ('METHANE', 'Methane')], max_length=20)),
                ('final_decision', models.CharField(choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('claim_alignment', models.CharField(max_length=20)),
                ('explanation', models.TextField()),
                ('decision_reasons', models.JSONField()),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_co2_tco2_year', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credits_issued', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=10)),
                ('image_file', models.ImageField(upload_to='projects/')),
                ('captured_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
    ]
