# Generated by Django 5.2.6 on 2026-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="claimed_improvement_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="project",
            name="project_coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_cost_lakh_inr",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="verification_metrics",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="verification_report",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="project",
            name="area_hectares",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="claim_alignment",
            field=models.CharField(
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="classification",
            field=models.CharField(
                choices=[
                    ("SOLAR", "Solar"),
                    ("VEGETATION", "Vegetation"),
                    ("PLANTATION", "Plantation"),
                    ("METHANE", "Methane"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="confidence_score",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="project",
            name="decision_reasons",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="project",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="final_decision",
            field=models.CharField(
                choices=[
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                    ("PENDING", "Pending"),
                    ("REVIEW_REQUIRED", "Review Required"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
