# Generated by Django 5.2.6 on 2026-01-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_coordinates",
        ),
        migrations.RemoveField(
            model_name="project",
            name="verification_metrics",
        ),
        migrations.RemoveField(
            model_name="project",
            name="verification_report",
        ),
        migrations.AddField(
            model_name="project",
            name="aqi_improvement_proxy",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="avoided_co2_tco2_year",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="claim_gap_pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimated_energy_mwh_year",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimated_panel_area_m2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="land_use_conflict",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mean_dice",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mean_iou",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ndvi_change",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_area_hectares",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Project area in hectares",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="soil_health_index",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="solar_probability",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="temporal_consistency",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vegetation_coverage_pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vegetation_growth_pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vegetation_score",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="verification_result_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="area_hectares",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="claim_alignment",
            field=models.CharField(
                blank=True,
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="claimed_improvement_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="User's claimed improvement percentage",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="confidence_score",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="decision_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="project",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="final_decision",
            field=models.CharField(
                choices=[
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                    ("REVIEW_REQUIRED", "Review Required"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_cost_lakh_inr",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Project cost in Lakh INR",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="report_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="captured_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("BEFORE", "Before"),
                    ("AFTER", "After"),
                    ("SATELLITE", "Satellite"),
                    ("DRONE", "Drone"),
                ],
                max_length=15,
            ),
        ),
    ]
