# Generated by Django 5.2.6 on 2026-01-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_integrate_ml_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="report_file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
