# Generated by Django 5.2.6 on 2026-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_add_report_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="blockchain_minted",
            field=models.BooleanField(
                default=False,
                help_text="Whether credits have been minted on blockchain",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="blockchain_tx_hash",
            field=models.CharField(
                blank=True,
                help_text="Transaction hash from blockchain credit minting",
                max_length=66,
                null=True,
            ),
        ),
    ]
