# Generated by Django 5.2.6 on 2026-03-19 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_add_new_domains_and_numeric_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("user", "project_name")},
        ),
    ]
