# Generated by Django 5.2.6 on 2026-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellorder",
            name="blockchain_tx_hash",
            field=models.CharField(
                blank=True,
                help_text="Transaction hash from blockchain sell order creation",
                max_length=66,
                null=True,
            ),
        ),
    ]
